// Code generated by internal/tools/tablegen from SKP_Silk_tables_*.c. DO NOT EDIT.

package tables

var TargetRate_table_NB = [8]int32{
	0, 8000, 9000, 11000, 13000, 16000,
	22000, 100000,
}
var TargetRate_table_MB = [8]int32{
	0, 10000, 12000, 14000, 17000, 21000,
	28000, 100000,
}
var TargetRate_table_WB = [8]int32{
	0, 11000, 14000, 17000, 21000, 26000,
	36000, 100000,
}
var TargetRate_table_SWB = [8]int32{
	0, 13000, 16000, 19000, 25000, 32000,
	46000, 100000,
}
var SNR_table_Q1 = [8]int32{
	19, 31, 35, 39, 43, 47,
	54, 64,
}
var SNR_table_one_bit_per_sample_Q7 = [4]int32{
	1984, 2240, 2408, 2708,
}
var SWB_detect_B_HP_Q13 = [3][3]int16{
	[3]int16{
		575, -948, 575,
	},
	[3]int16{
		575, -221, 575,
	},
	[3]int16{
		575, 104, 575,
	},
}
var SWB_detect_A_HP_Q13 = [3][2]int16{
	[2]int16{
		14613, 6868,
	},
	[2]int16{
		12883, 7337,
	},
	[2]int16{
		11586, 7911,
	},
}
var Dec_A_HP_24 = [2]int16{
	-16220, 8030,
}
var Dec_B_HP_24 = [3]int16{
	8000, -16000, 8000,
}
var Dec_A_HP_16 = [2]int16{
	-16127, 7940,
}
var Dec_B_HP_16 = [3]int16{
	8000, -16000, 8000,
}
var Dec_A_HP_12 = [2]int16{
	-16043, 7859,
}
var Dec_B_HP_12 = [3]int16{
	8000, -16000, 8000,
}
var Dec_A_HP_8 = [2]int16{
	-15885, 7710,
}
var Dec_B_HP_8 = [3]int16{
	8000, -16000, 8000,
}
var Lsb_CDF = [3]uint16{
	0, 40000, 65535,
}
var LTPscale_CDF = [4]uint16{
	0, 32000, 48000, 65535,
}
var Vadflag_CDF = [3]uint16{
	0, 22000, 65535,
}
var SamplingRates_table = [4]int32{
	8, 12, 16, 24,
}
var SamplingRates_CDF = [5]uint16{
	0, 16000, 32000, 48000, 65535,
}
var NLSF_interpolation_factor_CDF = [6]uint16{
	0, 3706, 8703, 19226, 30926, 65535,
}
var FrameTermination_CDF = [5]uint16{
	0, 20000, 45000, 56000, 65535,
}
var Seed_CDF = [5]uint16{
	0, 16384, 32768, 49152, 65535,
}
var Quantization_Offsets_Q10 = [2][2]int16{
	[2]int16{
		32, 100,
	},
	[2]int16{
		100, 256,
	},
}
var LTPScales_table_Q14 = [3]int16{
	15565, 11469, 8192,
}
var Transition_LP_B_Q28 = [5][3]int32{
	[3]int32{
		250767114, 501534038, 250767114,
	},
	[3]int32{
		209867381, 419732057, 209867381,
	},
	[3]int32{
		170987846, 341967853, 170987846,
	},
	[3]int32{
		131531482, 263046905, 131531482,
	},
	[3]int32{
		89306658, 178584282, 89306658,
	},
}
var Transition_LP_A_Q28 = [5][2]int32{
	[2]int32{
		506393414, 239854379,
	},
	[2]int32{
		411067935, 169683996,
	},
	[2]int32{
		306733530, 116694253,
	},
	[2]int32{
		185807084, 77959395,
	},
	[2]int32{
		35497197, 57401098,
	},
}

const LTPscale_offset int32 = 2
const Vadflag_offset int32 = 1
const SamplingRates_offset int32 = 2
const NLSF_interpolation_factor_offset int32 = 4
const FrameTermination_offset int32 = 2
const Seed_offset int32 = 2
