// Code generated by internal/tools/tablegen from SKP_Silk_tables_*.c. DO NOT EDIT.

package tables

var Type_offset_CDF = [5]uint16{
	0, 37522, 41030, 44212, 65535,
}
var Type_offset_joint_CDF = [4][5]uint16{
	[5]uint16{
		0, 57686, 61230, 62358, 65535,
	},
	[5]uint16{
		0, 18346, 40067, 43659, 65535,
	},
	[5]uint16{
		0, 22694, 24279, 35507, 65535,
	},
	[5]uint16{
		0, 6067, 7215, 13010, 65535,
	},
}

const Type_offset_CDF_offset int32 = 2
